// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rovers4.Data;

namespace Rovers4.Migrations
{
    [DbContext(typeof(ClubContext))]
    [Migration("20200905122530_AddedPhotosToClubAndTeam")]
    partial class AddedPhotosToClubAndTeam
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rovers4.Models.Club", b =>
                {
                    b.Property<int>("ClubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("ClubImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClubImage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClubImage3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("ClubID");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            ClubID = 1,
                            Address = "Bushy Park",
                            Email = "X00152190@mytudublin.ie",
                            Name = "Ratharnham Rovers",
                            Number = "0872878566"
                        });
                });

            modelBuilder.Entity("Rovers4.Models.Fixture", b =>
                {
                    b.Property<int>("FixtureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FixtureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FixtureType")
                        .HasColumnType("int");

                    b.Property<int>("HomeOrAway")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MeetTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Opponent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OpponentScore")
                        .HasColumnType("int");

                    b.Property<int?>("OurScore")
                        .HasColumnType("int");

                    b.Property<int>("ResultDescription")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("FixtureID");

                    b.HasIndex("TeamID");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("Rovers4.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MgmtRole")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonBio")
                        .HasColumnType("nvarchar(1280)")
                        .HasMaxLength(1280);

                    b.Property<int>("PersonType")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<int>("PlayerStatID")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerStatID1")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.HasIndex("PlayerStatID1");

                    b.HasIndex("TeamID");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            DOB = new DateTime(2080, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Ronan",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 0,
                            PlayerPosition = 1,
                            PlayerStatID = 0,
                            Surname = "Breen",
                            TeamID = 1,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        },
                        new
                        {
                            PersonID = 2,
                            DOB = new DateTime(2080, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Ronan",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 0,
                            PlayerPosition = 0,
                            PlayerStatID = 0,
                            Surname = "Grey",
                            TeamID = 1,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        },
                        new
                        {
                            PersonID = 3,
                            DOB = new DateTime(2080, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Richard",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 0,
                            PlayerPosition = 2,
                            PlayerStatID = 0,
                            Surname = "Breen",
                            TeamID = 1,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        },
                        new
                        {
                            PersonID = 4,
                            DOB = new DateTime(2080, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Andrew",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 0,
                            PlayerPosition = 3,
                            PlayerStatID = 0,
                            Surname = "Breen",
                            TeamID = 1,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        },
                        new
                        {
                            PersonID = 5,
                            DOB = new DateTime(2080, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Murray",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 0,
                            PlayerPosition = 1,
                            PlayerStatID = 0,
                            Surname = "Breen",
                            TeamID = 1,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        },
                        new
                        {
                            PersonID = 6,
                            DOB = new DateTime(2080, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Patricia",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 0,
                            PlayerPosition = 0,
                            PlayerStatID = 0,
                            Surname = "Breen",
                            TeamID = 1,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        },
                        new
                        {
                            PersonID = 7,
                            DOB = new DateTime(2080, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Elmond",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            MgmtRole = 0,
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 1,
                            PlayerStatID = 0,
                            Surname = "Breen",
                            TeamID = 1,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        },
                        new
                        {
                            PersonID = 8,
                            DOB = new DateTime(2080, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Tim",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 0,
                            PlayerPosition = 0,
                            PlayerStatID = 0,
                            Surname = "Breen",
                            TeamID = 2,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        },
                        new
                        {
                            PersonID = 9,
                            DOB = new DateTime(2080, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Tom",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 0,
                            PlayerPosition = 1,
                            PlayerStatID = 0,
                            Surname = "Grey",
                            TeamID = 2,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        },
                        new
                        {
                            PersonID = 10,
                            DOB = new DateTime(1980, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Trevor",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 0,
                            PlayerPosition = 2,
                            PlayerStatID = 0,
                            Surname = "Breen",
                            TeamID = 2,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        },
                        new
                        {
                            PersonID = 11,
                            DOB = new DateTime(1980, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Tilly",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 0,
                            PlayerPosition = 3,
                            PlayerStatID = 0,
                            Surname = "Breen",
                            TeamID = 3,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        },
                        new
                        {
                            PersonID = 12,
                            DOB = new DateTime(1980, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Tyrance",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 0,
                            PlayerPosition = 0,
                            PlayerStatID = 0,
                            Surname = "Breen",
                            TeamID = 3,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        },
                        new
                        {
                            PersonID = 13,
                            DOB = new DateTime(1980, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Tombo",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 0,
                            PlayerPosition = 1,
                            PlayerStatID = 0,
                            Surname = "Breen",
                            TeamID = 3,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        },
                        new
                        {
                            PersonID = 14,
                            DOB = new DateTime(1980, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "X@X.com",
                            FirstName = "Timo",
                            Image = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Mobile = "111 1111111",
                            PersonBio = "Alan Mannus began his career with Linfield where he won five league titles in nine years. He joined Shamrock Rovers in August 2009, making his first appearance in a 2-2 draw against Dundalk in Tallaght. Mannus won the 2010 SWAI Goalkeeper of the Year the following season as Rovers won the league for the first time in 16 years.The club lifted the Setanta Cup trophy in May 2011 but he moved to St Johnstone two months later, making his last appearance in a Hoops jersey in a Champions League tie away to Flora Tallinn. Mannus debuted against Hearts the following February and played a total of 191 league games in Scotland, helping the Saints to their first ever Scottish Cup in 2014. The Northern Ireland goalkeeper made his international debut in 2004 and was part of former Hoops manager Michael O’Neill’s Euro 2016 squad in France. Alan rejoined the Hoops in the summer of 2018.He spoke to Hoops Scene a the start of our 2019 Europa League campaign",
                            PersonType = 1,
                            PlayerPosition = 3,
                            PlayerStatID = 0,
                            Surname = "Breen",
                            TeamID = 3,
                            ThumbnailImage = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
                        });
                });

            modelBuilder.Entity("Rovers4.Models.PlayerStat", b =>
                {
                    b.Property<int>("PlayerStatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("CleanSheet")
                        .HasColumnType("int");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int>("MotmAward")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<int>("RedCards")
                        .HasColumnType("int");

                    b.HasKey("PlayerStatID");

                    b.ToTable("PlayerStats");

                    b.HasData(
                        new
                        {
                            PlayerStatID = 1,
                            Assists = 5,
                            CleanSheet = 0,
                            GamesPlayed = 5,
                            Goals = 3,
                            MotmAward = 3,
                            PersonID = 1,
                            RedCards = 2
                        },
                        new
                        {
                            PlayerStatID = 2,
                            Assists = 1,
                            CleanSheet = 0,
                            GamesPlayed = 3,
                            Goals = 1,
                            MotmAward = 1,
                            PersonID = 2,
                            RedCards = 0
                        },
                        new
                        {
                            PlayerStatID = 3,
                            Assists = 2,
                            CleanSheet = 0,
                            GamesPlayed = 2,
                            Goals = 2,
                            MotmAward = 2,
                            PersonID = 3,
                            RedCards = 2
                        },
                        new
                        {
                            PlayerStatID = 4,
                            Assists = 5,
                            CleanSheet = 0,
                            GamesPlayed = 3,
                            Goals = 3,
                            MotmAward = 3,
                            PersonID = 4,
                            RedCards = 2
                        },
                        new
                        {
                            PlayerStatID = 5,
                            Assists = 5,
                            CleanSheet = 0,
                            GamesPlayed = 5,
                            Goals = 3,
                            MotmAward = 3,
                            PersonID = 5,
                            RedCards = 2
                        },
                        new
                        {
                            PlayerStatID = 6,
                            Assists = 5,
                            CleanSheet = 0,
                            GamesPlayed = 5,
                            Goals = 3,
                            MotmAward = 3,
                            PersonID = 6,
                            RedCards = 2
                        },
                        new
                        {
                            PlayerStatID = 7,
                            Assists = 5,
                            CleanSheet = 0,
                            GamesPlayed = 5,
                            Goals = 3,
                            MotmAward = 3,
                            PersonID = 7,
                            RedCards = 2
                        },
                        new
                        {
                            PlayerStatID = 8,
                            Assists = 5,
                            CleanSheet = 0,
                            GamesPlayed = 5,
                            Goals = 3,
                            MotmAward = 3,
                            PersonID = 8,
                            RedCards = 2
                        },
                        new
                        {
                            PlayerStatID = 9,
                            Assists = 5,
                            CleanSheet = 0,
                            GamesPlayed = 5,
                            Goals = 3,
                            MotmAward = 3,
                            PersonID = 9,
                            RedCards = 2
                        },
                        new
                        {
                            PlayerStatID = 10,
                            Assists = 5,
                            CleanSheet = 0,
                            GamesPlayed = 5,
                            Goals = 3,
                            MotmAward = 3,
                            PersonID = 10,
                            RedCards = 2
                        },
                        new
                        {
                            PlayerStatID = 11,
                            Assists = 5,
                            CleanSheet = 0,
                            GamesPlayed = 5,
                            Goals = 3,
                            MotmAward = 3,
                            PersonID = 11,
                            RedCards = 2
                        },
                        new
                        {
                            PlayerStatID = 12,
                            Assists = 5,
                            CleanSheet = 0,
                            GamesPlayed = 5,
                            Goals = 3,
                            MotmAward = 3,
                            PersonID = 12,
                            RedCards = 2
                        },
                        new
                        {
                            PlayerStatID = 13,
                            Assists = 5,
                            CleanSheet = 0,
                            GamesPlayed = 5,
                            Goals = 3,
                            MotmAward = 3,
                            PersonID = 13,
                            RedCards = 2
                        },
                        new
                        {
                            PlayerStatID = 14,
                            Assists = 5,
                            CleanSheet = 0,
                            GamesPlayed = 5,
                            Goals = 3,
                            MotmAward = 3,
                            PersonID = 14,
                            RedCards = 2
                        });
                });

            modelBuilder.Entity("Rovers4.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClubID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("TeamBio")
                        .HasColumnType("nvarchar(1280)")
                        .HasMaxLength(1280);

                    b.Property<string>("TeamImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamID");

                    b.HasIndex("ClubID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamID = 1,
                            ClubID = 1,
                            Name = "First Team",
                            TeamBio = "First Team Compete in Leinster Senior League 2. They have been together since 2014 and recently appointed Mike Bassett for the new season."
                        },
                        new
                        {
                            TeamID = 2,
                            ClubID = 1,
                            Name = "Under 21s",
                            TeamBio = "The Under 21 Team Compete in Leinster Senior League 1. They have been together since 2015."
                        },
                        new
                        {
                            TeamID = 3,
                            ClubID = 1,
                            Name = "Under 19s",
                            TeamBio = "The Under 19 Team Compete in Leinster Senior League 3. They have been together since 2014."
                        },
                        new
                        {
                            TeamID = 4,
                            ClubID = 1,
                            Name = "Under 17s",
                            TeamBio = "The Under 17 Team Compete in Leinster Senior League 2. They have been together since 2013."
                        },
                        new
                        {
                            TeamID = 5,
                            ClubID = 1,
                            Name = "Under 15s",
                            TeamBio = "The Under 15 Team Compete in Leinster Senior League 2. They have been together since 2014."
                        },
                        new
                        {
                            TeamID = 6,
                            ClubID = 1,
                            Name = "Under 13s",
                            TeamBio = "The Under 13 Team Compete in Leinster Senior League 2. They have been together since 2014."
                        },
                        new
                        {
                            TeamID = 7,
                            ClubID = 1,
                            Name = "Under 11s",
                            TeamBio = "The Under 11 Team Compete in Leinster Senior League 2. They have been together since 2014."
                        });
                });

            modelBuilder.Entity("Rovers4.Models.Fixture", b =>
                {
                    b.HasOne("Rovers4.Models.Team", "Team")
                        .WithMany("fixtures")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rovers4.Models.Person", b =>
                {
                    b.HasOne("Rovers4.Models.PlayerStat", "PlayerStat")
                        .WithMany()
                        .HasForeignKey("PlayerStatID1");

                    b.HasOne("Rovers4.Models.Team", "Team")
                        .WithMany("Staff")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rovers4.Models.Team", b =>
                {
                    b.HasOne("Rovers4.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
